In [3]:
import pandas as pd

pd.read_excel('CAORAN.xlsx')

,observation_date,CAORAN7POP,GDPALL06059,REALGDPALL06059,CANGSP,CARGSP,LAUCN060590000000003A,LAUCN060590000000005A,MHICA06059A052NCEN
0,1970,1421.233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1971,1484.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1972,1536.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1973,1607.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1974,1669.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1975,1725.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1976,1772.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1977,1812.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1978,1853.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1979,1892.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1980,1932.921,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1981,2004.806,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1982,2045.925,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1983,2088.886,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1984,2123.362,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1985,2171.930,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1986,2228.895,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1987,2281.486,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1988,2333.101,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1989,2383.920,NaN,NaN,NaN,NaN,NaN,NaN,39592.0
20,1990,2418.986,NaN,NaN,NaN,NaN,3.5,1305545.0,NaN
21,1991,2452.691,NaN,NaN,NaN,NaN,5.3,1251290.0,NaN
22,1992,2497.014,NaN,NaN,NaN,NaN,6.7,1240988.0,NaN
23,1993,2532.639,NaN,NaN,NaN,NaN,6.8,1236273.0,45116.0
24,1994,2566.599,NaN,NaN,NaN,NaN,5.8,1256115.0,NaN
25,1995,2603.678,NaN,NaN,NaN,NaN,5.1,1255072.0,48701.0
26,1996,2643.996,NaN,NaN,NaN,NaN,4.2,1275059.0,NaN
27,1997,2709.277,NaN,NaN,NaN,NaN,3.3,1328578.0,49583.0
28,1998,2773.187,NaN,NaN,NaN,NaN,2.9,1386214.0,50986.0
29,1999,2815.933,NaN,NaN,NaN,NaN,2.7,1423834.0,52129.0
30,2000,2856.241,NaN,NaN,NaN,NaN,3.5,1428975.0,55654.0
31,2001,2890.684,NaN,NaN,NaN,NaN,4.0,1449080.0,55994.0
32,2002,2917.162,NaN,NaN,NaN,NaN,5.0,1447724.0,55992.0
33,2003,2941.573,NaN,NaN,NaN,NaN,4.8,1470827.0,55909.0
34,2004,2956.461,NaN,NaN,NaN,NaN,4.2,1502003.0,58605.0
35,2005,2957.404,NaN,NaN,NaN,NaN,3.7,1527005.0,65823.0
36,2006,2952.610,NaN,NaN,NaN,NaN,3.4,1546035.0,70109.0
37,2007,2957.307,NaN,NaN,NaN,NaN,3.8,1546709.0,73107.0
38,2008,2988.541,NaN,NaN,NaN,NaN,5.3,1530120.0,74862.0
39,2009,3023.265,NaN,NaN,NaN,NaN,9.0,1451508.0,71735.0
40,2010,3016.376,NaN,NaN,NaN,NaN,10.0,1383916.0,70727.0
41,2011,3050.199,NaN,NaN,NaN,NaN,9.3,1400874.0,72046.0
42,2012,3078.710,NaN,NaN,NaN,NaN,8.0,1433508.0,71866.0
43,2013,3105.262,NaN,NaN,NaN,NaN,6.7,1455311.0,73827.0
44,2014,3126.523,NaN,NaN,NaN,NaN,5.6,1478476.0,76061.0
45,2015,3148.952,NaN,NaN,NaN,NaN,4.5,1513060.0,78002.0
46,2016,3164.277,NaN,NaN,NaN,NaN,4.1,1532725.0,81642.0
47,2017,3174.159,244438165.0,244438165.0,2740550.3,2740550.3,3.5,1549003.0,86031.0
48,2018,3175.579,256068837.0,251165771.0,2899530.9,2850970.3,3.0,1568273.0,89373.0
49,2019,3170.851,269080278.0,257959284.0,3062158.9,2962792.1,2.8,1571261.0,95761.0
50,2020,3185.516,268778347.0,252505652.0,3068809.4,2925146.9,8.9,1426971.0,98786.0
51,2021,3161.005,294339604.0,268128135.0,3416939.4,3146185.3,6.0,1467342.0,100210.0
52,2022,3151.184,314177082.0,270440831.0,3641643.4,3167460.8,3.2,1540561.0,106047.0